---
title: 'Project 1: What made you happy today?'
output:
  html_document:
    df_print: paged
  pdf_document: default
---
```{r echo=FALSE, message=FALSE}
## library packages
library(dplyr)
library(ggplot2)
library(tm)
library(wordcloud2)
library(RColorBrewer)
library(tidytext)
library(tidyverse)
```

```{r echo=FALSE}
## combine two datasets
demo <- read.csv("../data/HappyDB/happydb/data/demographic.csv")
HM <- read.csv("../output//processed_moments.csv")
mydata <- as.data.frame(full_join(demo, HM, by = "wid"))
```

## What's the happiest moment?

```{r echo=FALSE}
mydata %>%   
  filter(!is.na(predicted_category)) %>%
  ggplot(., aes(x = reorder(predicted_category, predicted_category, function(x) length(x)))) + 
    geom_bar(fill = rep(brewer.pal(7,'YlOrRd'),each = 1)) + 
    coord_flip() +
    theme(axis.title.y=element_blank())
```

The ranking says most people feel happy due to affection. And the number of happy moments with achievement are pretty close to the affection. 

## What do people focus on?
### Is there any difference nationalities?

### How about genders?
```{r warning=FALSE, echo=FALSE}
dataF <- mydata[mydata$gender == "f",]
dataM <- mydata[mydata$gender == "m",]

## female
docsF <- Corpus(VectorSource(dataF$text))
docsF <- tm_map(docsF, stripWhitespace)
docsF <- tm_map(docsF, content_transformer(tolower))
docsF <- tm_map(docsF, removeWords, stopwords("english"))
docsF <- tm_map(docsF, removeWords, c("time", "day"))
docsF <- tm_map(docsF, removeWords, character(0))
docsF <- tm_map(docsF, removePunctuation)

tdmF <-TermDocumentMatrix(docsF)
tdmF.tidy <- tidy(tdmF)
word.docsF <- summarise(group_by(tdmF.tidy, term), freq = sum(count))
word.docsF <- as.data.frame(word.docsF)
word.docsF <- word.docsF[order(word.docsF$freq, decreasing = TRUE), ]

figPathf = system.file("examples/female.png", package = "wordcloud2")
wordcloud2(word.docsF, figPath = figPathf)
```

```{r warning=FALSE, echo=FALSE}
## male
docsM <- Corpus(VectorSource(dataM$text))
docsM <- tm_map(docsM, stripWhitespace)
docsM <- tm_map(docsM, content_transformer(tolower))
docsM <- tm_map(docsM, removeWords, stopwords("english"))
docsM <- tm_map(docsM, removeWords, c("time", "day"))
docsM <- tm_map(docsM, removeWords, character(0))
docsM <- tm_map(docsM, removePunctuation)

tdmM <-TermDocumentMatrix(docsM)
tdmM.tidy <- tidy(tdmM)
word.docsM <- summarise(group_by(tdmM.tidy, term), freq = sum(count))
word.docsM <- as.data.frame(word.docsM)
word.docsM <- word.docsM[order(word.docsM$freq, decreasing = TRUE), ]

figPathm = system.file("examples/male.png", package = "wordcloud2")
wordcloud2(word.docsM, figPath = figPathm)
```
